service: todoservice
# app and org for use with dashboard.serverless.com
app: newstore
org: xzirez

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["ProductsTable", "Arn"] }

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  createTodo:
    handler: bin/functions/createTodo/main
    events:
      - httpApi:
          path: /createTodo
          method: post
  getTodo:
    handler: bin/functions/getTodo/main
    events:
      - httpApi:
          path: /todo
          method: get
  updateTodo: 
      handler: bin/functions/updateTodo/main
      events:
      - httpApi:
          path: /updateTodo
          method: put
  deleteTodo: 
      handler: bin/functions/deleteTodo/main
      events:
      - httpApi:
          path: /deleteTodo
          method: delete

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
